### ISSUE TITLE
terminator的python-nautilus脚本不工作

### ISSUE THREAD

**Issue by nandttl** [dwSun/utils#1]
不管是您改的版本还是python-nautilus自带的open terminal例子脚本都不工作，但是另外一个例子脚本submenu是有效果的，请问你遇到过这个问题么？

**Comment by dwSun** [comment]
不知道什么情况，可以试试在命令行里面启动nautilus，可以看到错误信息。

**Comment by nandttl** [comment]
感谢，找到问题了，python提示cannot import name GConf，安装相关依赖库后解决了
